"""add_account_id_to_invoices

Revision ID: b325610226a8
Revises: a0c9d9f0325d
Create Date: 2025-08-27 11:09:42.871170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b325610226a8'
down_revision: Union[str, Sequence[str], None] = 'a0c9d9f0325d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add account_id column to invoices table
    op.add_column('invoices', sa.Column('account_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_invoices_account_id'), 'invoices', ['account_id'], unique=False)
    
    # Update existing invoices with default account_id
    op.execute("UPDATE invoices SET account_id = 'TestAccount' WHERE account_id IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_account_id'), table_name='invoices')
    op.drop_column('invoices', 'account_id')
    # ### end Alembic commands ###
